### ISSUE TITLE
Starting UI

### ISSUE THREAD

**Issue by arukaen** [pinterest/pinball#21]
Getting the following error when trying to start the UI:

```
[2015-03-19 Thu 16:01:23] - pinball.ui.cache_thread - INFO    "Workflow data computation starting."
[2015-03-19 Thu 16:01:23] - pinball.ui.cache_thread - ERROR   "'WorkflowSchedule' object has no attribute 'workflows_config'"
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pinball/ui/cache_thread.py", line 67, in _compute_workflow
    schedules_data = data_builder.get_schedules()
  File "/usr/local/lib/python2.7/dist-packages/pinball/ui/data_builder.py", line 862, in get_schedules
    workflows_config=schedule.workflows_config,
AttributeError: 'WorkflowSchedule' object has no attribute 'workflows_config'
[2015-03-19 Thu 16:01:23] - pinball.ui.cache_thread - INFO    "Workflow data computation starting."
```

I also get this error on schedules:

```
An error occurred on the server: INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pinball/ui/views.py", line 201, in schedules
    schedules_data = data_builder.get_schedules()
  File "/usr/local/lib/python2.7/dist-packages/pinball/ui/data_builder.py", line 862, in get_schedules
    workflows_config=schedule.workflows_config,
AttributeError: 'WorkflowSchedule' object has no attribute 'workflows_config'
```

**Comment by arukaen** [comment]
Looking @ class WorkflowSchedule(Schedule):
    """Schedule for a workflow."""
    def __init__(
            self,
            next_run_time=None,
            recurrence_seconds=None,
            overrun_policy=OverrunPolicy.SKIP,
            parser_params=PinballConfig.PARSER_PARAMS,
            workflow=None,
            emails=None,
            max_running_instances=None):
        Schedule.__init__(self, next_run_time, recurrence_seconds,
                          overrun_policy)
        self.parser_params = parser_params
        self.workflow = workflow
        self.emails = emails if emails is not None else []

Does not contain a workflows_config attribute.

**Comment by MaoYe** [comment]
Thanks for reporting this. Will check this issue and update here soon

**Comment by MaoYe** [comment]
this issue has been fixed, thanks @arukaen !
