### ISSUE TITLE
TypeError: can only concatenate list (not "tuple") to list

### ISSUE THREAD

**Issue by golharam** [pinterest/pinball#65]
I just installed pinball and am trying to get it up and running on CentOS 6. When I run 

 python -m pinball.run_pinball -c ./default.yaml -m master                 

I get:

Traceback (most recent call last):
  File "/apps/sys/python/2.7.8/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/apps/sys/python/2.7.8/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/golharr/workspace/pinball/pinball/run_pinball.py", line 26, in <module>
    from pinball.config.pinball_config import PinballConfig
  File "pinball/config/pinball_config.py", line 28, in <module>
    class PinballConfig(object):
  File "pinball/config/pinball_config.py", line 97, in PinballConfig
    'django.core.context_processors.request',
TypeError: can only concatenate list (not "tuple") to list

**Comment by csliu** [comment]
this has been fixed in 0.2.10
