### ISSUE TITLE
When installing from source

### ISSUE THREAD

**Issue by golharam** [pinterest/pinball#66]
When building from source using 'python setup.py install --user', I get this error:

Installed /home/golharr/.local/lib/python2.7/site-packages/pinball-0.2.9-py2.7.egg
Processing dependencies for pinball==0.2.9
Traceback (most recent call last):
  File "setup.py", line 81, in <module>
    test_suite='tests',
  File "/apps/sys/python/2.7.8/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/apps/sys/python/2.7.8/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/apps/sys/python/2.7.8/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/install.py", line 67, in run
  File "build/bdist.linux-x86_64/egg/setuptools/command/install.py", line 117, in do_egg_install
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 370, in run
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 594, in easy_install
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 645, in install_item
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 704, in process_distribution
TypeError: not enough arguments for format string

**Comment by csliu** [comment]
it seems not related to pinball but just easy_install issue: https://github.com/pypa/setuptools/issues/281

I also can't reproduce this issue. can you upgrade your setuptools and retry?
